In [1]:
#creat a numpy array
import numpy as np 

arr = np.array([1,2,3,4,5])

print(arr)
print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
# creation of 0D array

import numpy as np

arr = np.array(42)
print(arr)

42


In [3]:
#creation of 1D array
import numpy as np 

arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [6]:
#creation of 2D array

import numpy as np 

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [7]:
#creation of 3D arrray
import numpy as np

arr = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])
print(arr)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


In [11]:
#finding which D array

import numpy as np 
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3,4,5],[6,7,8,9,10]])
d = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])
e = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)


0
1
2
3
2


In [12]:
#access array elements
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr[1])

2


In [13]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[0])

1


In [14]:
#adding index of array

import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[2]+arr[3])

7


In [16]:
# access 2D arra
import numpy as np 
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("2nd element on 1st row:",arr[0,3])

2nd element on 1st row: 4


In [1]:
#slicing1
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [2]:
#slicing2
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[:5])

[1 2 3 4 5]


In [3]:
#slicing3
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[:])

[1 2 3 4 5 6 7]


In [4]:
#slicing4
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[4:])

[5 6 7]


In [5]:
#slicing5
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[:4])

[1 2 3 4]


In [9]:
#slicing from opp side
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

[5 6]


In [13]:
#slicing step
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:6:2])

[2 4 6]


In [14]:
#slicing step2
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]
